// Generated by "bundle-dts@1.1.3" https://github.com/fishen/bundle-dts#readme."
declare module "swagger-code-generate/src/config" {
    export interface IConfig {
        injection?: Record<string, string>;
        destination?: string;
        decorators?: string[];
        defaults?: string[];
        rename?: Partial<Record<'method' | 'parameterType' | 'responseType', (...args: any) => string>>;
        templates?: Partial<Record<'type' | 'index', string>>;
        ignores?: Partial<Record<'definitions' | 'body' | 'header' | 'query', string[]>>;
        imports?: string[];
        filename?: (args: {
            name: string;
        }) => string;
        classname?: (args: {
            name: string;
        }) => string;
        name?: string;
        source?: string;
        systemGenericTypes?: string[];
        typeMappings?: Record<string, string>;
    }
    export const defaultConfig: IConfig;
}
declare module "swagger-code-generate/src/swagger" {
    export interface ISwaggerInfo {
        version: string;
        title: string;
    }
    export interface ISwaggerDefinitionProperty {
        example?: string;
        format?: string;
        description?: string;
        type?: string;
        $ref?: string;
        items?: ISwaggerDefinitionProperty;
    }
    export interface ISwaggerDefinition {
        properties: Record<string, ISwaggerDefinitionProperty>;
        required?: string[];
        type: string;
        title: string;
        additionalProperties?: Record<'type', any>;
    }
    export interface ISwaggerPathParameter {
        default: any;
        description: string;
        in: 'header' | 'body' | 'query';
        name: string;
        required: boolean;
        type: string;
    }
    export interface ISwaggerPathResponse {
        description: string;
        schema?: ISwaggerDefinitionProperty;
    }
    export interface ISwaggerPath {
        consumes: string[];
        operationId: string;
        parameters: ISwaggerPathParameter[];
        produces: string[];
        responses: Record<number, ISwaggerPathResponse>;
        summary: string;
        tags: string[];
        deprecated?: boolean;
    }
    export interface ISwaggerTag {
        name: string;
        description: string;
    }
    export interface ISwagger {
        basePath: string;
        definitions: Record<string, ISwaggerDefinition>;
        host: string;
        info: ISwaggerInfo;
        paths: Record<string, Record<string, ISwaggerPath>>;
        swagger: string;
        tags: ISwaggerTag[];
    }
}
declare module "swagger-code-generate/src/property" {
    import { ISwaggerDefinitionProperty } from 'swagger-code-generate/src/swagger';
    import { IConfig } from 'swagger-code-generate/src/config';
    export class Property {
        name: string;
        type: string;
        description: string;
        default: any;
        deprecated: boolean;
        required: boolean;
        generic: boolean;
        otherType: boolean;
        constructor(data: ISwaggerDefinitionProperty & {
            name: string;
            default?: any;
            required?: any;
        }, config: IConfig);
    }
}
declare module "swagger-code-generate/src/definition" {
    import { Property } from 'swagger-code-generate/src/property';
    import { IConfig } from 'swagger-code-generate/src/config';
    import { ISwagger, ISwaggerDefinition } from 'swagger-code-generate/src/swagger';
    export class Definition {
        title: string;
        type: string;
        generic: boolean;
        name: string;
        basePath: string;
        host: string;
        properties?: Property[];
        genericProperties?: string[];
        constructor(data: ISwaggerDefinition, config: IConfig);
        static parse(swagger: ISwagger, config: IConfig): Definition[];
    }
}
declare module "swagger-code-generate/src/param" {
    import { Property } from 'swagger-code-generate/src/property';
    import { Method } from 'swagger-code-generate/src/method';
    import { IConfig } from 'swagger-code-generate/src/config';
    import { ISwaggerPathParameter } from 'swagger-code-generate/src/swagger';
    export class Param {
        name: string;
        type: string;
        in: 'body' | 'query' | 'header';
        properties: Property[];
        typeName: string;
        referenced: boolean;
        required?: boolean;
        constructor(data: {
            name: string;
            type: string;
            in: 'body' | 'query' | 'header';
            properties?: Property[];
        });
        static from(method: Method, params: ISwaggerPathParameter[], config: IConfig): Param[];
    }
}
declare module "swagger-code-generate/src/method" {
    import { Param } from 'swagger-code-generate/src/param';
    import { IConfig } from 'swagger-code-generate/src/config';
    import { ISwagger, ISwaggerPath } from 'swagger-code-generate/src/swagger';
    import { Definition } from 'swagger-code-generate/src/definition';
    export class Method {
        method: string;
        path: string;
        url: string;
        deprecated: boolean;
        operationId: string;
        summary: string;
        tags?: string[];
        name: string;
        parameters: Param[];
        defaults?: {
            key: string;
            value: string[];
        }[];
        response: string;
        constructor(data: ISwaggerPath & {
            path: string;
            method: string;
        }, config: IConfig, swagger: ISwagger);
        setDefault(param: Param, defaults: string[]): void;
        static parse(swagger: ISwagger, definitions: Definition[], config: IConfig): Method[];
    }
}
declare module "swagger-code-generate/src/generator" {
    import { IConfig } from 'swagger-code-generate/src/config';
    export class Generator {
        genericTypes: Map<any, any>;
        config: IConfig;
        constructor(config: IConfig);
        static render(view: object, template: string, filename: string, config: IConfig): any;
        static getType(a: {
            type?: string;
            $ref?: string;
            items?: object;
            schema?: object;
        }, config: IConfig): string;
        generate(): Promise<any>;
    }
}
declare module "swagger-code-generate/src/http" {
    export interface IHttp {
        /**
         * Make a HTTP request operation.
         * @param options The parameters required by the request.
         */
        request(options: {
            url: string;
            method: string;
            query?: Record<string, any>;
            body?: Record<string, any>;
            header?: Record<string, any>;
        }): Promise<any>;
        /**
         * Get the default value
         * @param name The param name
         * @param from The param source 'query','body','header'.
         * @param url The api url string.
         */
        getDefaultValue?(name: string, from: string, url: string): any;
    }
}
declare module "swagger-code-generate" {
    import { IHttp } from 'swagger-code-generate/src/http';
    import { IConfig } from 'swagger-code-generate/src/config';
    export function generate(config: Record<string, IConfig>): Promise<any>;
    export type { IConfig, IHttp };
}